UI 및 통신 후 깨지는 style 수정
wecode-bootcamp-korea/31-2nd-bbooing-frontend pull request #11
Opened 2022-04-19 06:33 UTC by Jaehyuksssss

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 UI를 완성
- 장바구니 데이터를 조회
- 장바구니 데이터를 제거
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. map function을 활용해서 반복되는 UI를 구현했습니다.
2. fetch의 get method 를 활용하여 데이터를 조회했습니다
3. fetch의 delete method 를 활용하여 데이터를 제거 했고 조건문을 써서 response가 ok이면 새로고침을 하지 않고도  랜더가 되게  구현했습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 지난번 프로젝트에는 데이터를 제거하면 새로고침을 해야만 나타나서 만족스럽지 못했는데 구현을 하게 되서 좋았다.
<br />

## :: 기타 질문 및 특이 사항
REBASE 해결하는데 도와주셔서 감사합니다.!

2022-04-20 01:39 UTC, younuk23 requested changes
PR 제목에서 무슨 작업을 했는지 알 수 있게 해주세요 지금의 
`ADD:UI 및 통신 후 깨지는 style 수정`
라는 제목은 무슨 UI를 추가했고 무슨 style을 수정했는지 알 수가 없네요
***
이 브랜치에서 한 작업이 아닌 Comment.js 파일이 같이 딸려온 것 같습니다.
작업분리 신경써주세요!!

2022-04-20 01:39 UTC, younuk23 commented on src/pages/WishList/WishList.js
> +  useEffect(() => {
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

2022-04-20 01:39 UTC, younuk23 commented on src/pages/WishList/WishList.js
> +    fetch('http://10.58.6.246:8000/carts/like')
api주소는 `config.js` 에서 관리하는 것으로 수정해주세요

API는 `config.js` 파일에서 일괄적으로 관리하면서 import, export 를 통해 사용하는 식으로 관리하는 것이 좋습니다. 그렇지 않을 경우, 백엔드 서버 IP 가 변경되면 fetch 함수를 일일이 찾아서 API 를 직접 수정해 주어야 하기 때문입니다.

아래는 config.js에서 API주소를 관리하는 하나의 예시입니다. 참고하셔서 팀원들과 논의 후 생각하신 방식으로 자유롭게 적용해주세요

```jsx
// src/config.js
const BASE_URL = 'http://10.58.5.151:8000'
const API = {
  product:`${BASE_URL}/products`,
  list:`${BASE_URL}/list`
}

// 사용하는 컴포넌트
import { API } from '../../../config.js';

...

fetch(`${API}/5`).then(...).then(...);
```

위의 경우, 백엔드 IP 가 바뀔 때 `config.js` 에서 IP 만 바꾸어주면 모든 API 가 새로운 IP 에 따라서 변경됩니다. 그렇기 때문에 일일이 fetch 함수를 찾아 API 를 수정해줄 필요가 없습니다.

2022-04-20 01:40 UTC, younuk23 commented
Git 관련해서 어려운 점 있으면 질문주세요!

2022-04-20 05:05 UTC, Jaehyuksssss commented on src/pages/WishList/WishList.js
> +    fetch('http://10.58.6.246:8000/carts/like')
넵!!

2022-04-21 09:00 UTC, Jaehyuksssss commented on src/pages/WishList/WishList.js
> +  }, []);
해결했습니다/.

2022-04-21 09:00 UTC, Jaehyuksssss commented on src/pages/WishList/WishList.js
> +        console.log(lectures);
해결했습니다/.

2022-04-21 09:00 UTC, Jaehyuksssss commented on src/pages/WishList/WishList.js
> +        console.log(res);
해결했습니다/.

2022-04-21 09:00 UTC, Jaehyuksssss commented on src/pages/WishList/WishComponent/WishContents.js
> +  console.log(lecture);
해결했습니다/.

2022-04-21 09:10 UTC, merged