[31기 김효정] 메인페이지 레이아웃 완료
wecode-bootcamp-korea/31-2nd-bbooing-frontend pull request #3
Opened 2022-04-14 04:13 UTC by hyodduru

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지 레이아웃 
- react slick library 활용하여 슬라이드 구현 
- 강의 카드로 구성된 공통 컴포넌트 레이아웃 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인페이지 레이아웃 
슬라이드, 강의 카드 컴포넌트로 구성된 메인페이지 레이아웃 
2. react slick library 활용하여 슬라이드 구현
react slick library와 styled component를 활용하여 메인 프로모션 슬라이드 및 강의 컴포넌트 모음으로 이루어진 슬라이드 구현
3. 강의 카드로 구성된 공통 컴포넌트 레이아웃  
전역으로 쓰일 강의 카드 component 레이아웃 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 처음으로 라이브러리를 사용해보았습니다. 어떻게 사용해야할지 몰라 공식문서와 기술블로그 등을 참고하여 코드를 작성했습니다. 처음에는 어색해서 원하는대로 스타일을 적용하는데 시간이 좀 걸렸지만 개발자 도구창에서 마크업구조와 스타일을 참고하며 계속 수정해보면서 조금씩 라이브러리를 사용하는데 익숙해질 수 있었습니다. 

- Styled Component 또한 처음으로 사용해보았습니다. 기존의 sass를 활용한 스타일 적용 방식이 이미 익숙해져있던터라 바로 Styled Component를 사용하기 좀 어색하고 어려웠지만 조금씩 익숙해지고 있습니다. 태그와 스타일 적용을 동시에 해줄 수 있어서 편리한 점이 있는 것 같지만 코드가 너무 길어지고 있는 느낌이 있어서 적는 방식에 있어서 조금 더 고민을 해봐야 할 것 같습니다. 

<br />

2022-04-14 06:50 UTC, younuk23 requested changes
- 고생하셨습니다 효정님 성장포인트도 너무 좋고, 코드도 전반적으로 깔끔하네요! 👍 
- 변수명에 대한 고민만 조금 더 하면 가독성이 더 좋아질 것 같습니다

2022-04-14 06:50 UTC, younuk23 commented on public/index.html
> +    ></script>
fontawesome 사용하실 때 script tag 이용해서 전체 폰트어썸을 다 가져와버리면 용량이 무거워집니다! 폰트어썸의 리액트용 패키지가 있어서 해당 패키지를 이용하시는게 필요한 부분만 설치해서 활용할 수 있어서 효율적입니다!

2022-04-14 06:50 UTC, younuk23 commented on src/components/Card/Card.js
> +  .category {
- styled-component를 이용해서 스타일링이 된 태그들은 해당 definition으로 이동해서 바로 스타일링을 확인이 가능한데 className으로 선언한 부분은 바로 definition으로 이동이 불가능해서 스타일링 파악하기에 어려움이 있음
- 위의 내용에 덧붙여서 className을 이용한 스타일링의 nesting depth가 깊어지는 경우에는 더 더욱 찾기가 힘들어짐
- depth가 깊어지는 경우 뿐만 아니라 1depth로도 className을 이용한 스타일 선언부가 길어지는 경우에도 해당 스타일링을 찾기 어려워짐
- 위의 사항들로 인해서 CSS in JS(styled-components 등)을 이용한 스타일링을 하는 경우에는 라이브러리 사용상 강제되는 등의 불가피한 부분을 제외하고는 className을 통한 스타일링은 최대한 지양하는게 권장됩니다.

2022-04-14 06:50 UTC, younuk23 commented on src/components/Card/Card.js
> +  ];
- 이 값 같은 경우에는 매 rendering 마다 새롭게 선언되고 할당될 필요는 없어보입니다.
- 이런 상수데이터를  함수형 컴포넌트 본문 안에서 선언하게 되면 rendering이 일어날때 마다 매번 데이터를 만들고 변수에 값을 할당하는 연산이 일어나게 됩니다.
- 따라서 성능에 악영향을 미칠 수 있습니다.
- 컴포넌트가 사용하는 데이터라고 컴포넌트 안에만 위치할 필요는 없습니다
- 통상 이런 상수데이터같은 경우에는 여러 컴포넌트에서 동시에 사용하는 데이터라면 별도 파일로 분리하거나,이 컴포넌트 안에서만 사용하는 데이터라면 컴포넌트 하단에 작성해줍니다
- 상수데이터의 네이밍은 상수데이터임을 표시하기 위해서 UPPERCASER + snake_case 로 작성해주는게 컨벤션입니다

2022-04-14 06:50 UTC, younuk23 commented on src/components/Card/Card.js
> +  const bgColor = Category_Color.find(list => list.type === categoryTag).color;
```suggestion
  const bgColor = Category_Color.find(({type}) => type === categoryTag).color;
```
- 구조분해할당 적용하면 조금 더 좋겠네요!! 별개로 상수데이터에는 color값이 들어가있지 않고 어떤 bg color를 설정할지는 styled components의 styling 부분에서 적용하는게 좀 더 관심사의 분리가 잘 된 코드같네요!! styled components가 type을 prop으로 받고 해당 prop을 이용해서 적절한 color를 매칭해주는식으로 처리하는게 좋겠네요! 이부분 이해 안되시면 오늘 라운지에서 찾아와주세요~!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Components/LectureSlide.js
> +
```suggestion
    const response = await fetch('/data/cardList.json');
    const data = await response.json();
```
() 이용해서 한줄로 처리하는 방법도 좋겠지만 위와 같이 나누어서 처리할 수도 있겠네요, 저는 개인적으로 가독성 측면에서 나눠서 적는것이 좋아보인다고 생각하는데 이부분은 개인마다, 회사마다, 팀마다 의견 및 컨벤션이 다를 수도 있어서 참고만 해주세요!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Components/LectureSlide.js
> +  const getData = async () => {
어떤 데이터를 가져오는 것인지 함수 이름에서 표현이 되면 좋겠네요!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Components/LectureSlide.js
> +        {cardList && cardList.map(card => <Card key={card.id} card={card} />)}
```suggestion
        {cardList?.map(card => <Card key={card.id} card={card} />)}
```
&&를 이용한 단축평가와 동일한 동작을 optional chaining 문법 이용해서 좀 더 간결하게 표현할 수도 있습니다. [공식문서](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 참고해서 어떻게 동작하는지 확인 및 이해해보시고 적용해보세요! 

2022-04-14 06:50 UTC, younuk23 commented on src/components/Card/Card.js
> +  .category {
라이브러리 커스텀을 위해서 어쩔 수 없는 경우를 제외하고는 스타일드 컴포넌트로 스타일링 진행해주세요!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Components/Promotion.js
> +const Promotion_Arr = [
```suggestion
const PROMOTIONS = [
```
- 상수데이터는 모두 UPPER_CASE + snake_case로 작성해주세요!
- Arr등의 데이터타입이 변수명에 붙어있는 건 좋지않습니다! 프로모션이 여러개들어있다라는 의미는 복수형 표현을 통해서 충분히 표현 가능합니다!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Main.js
> +  const clickHandler = id => setCurrentId(id);
clickHandler와 setCurrentID가 결국 동일한 동작을 하는 함수같네요! 굳이 함수를 하나 더 선언할 필요는 없어보입니다!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Main.js
> +};
👍

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Main.js
> +};
무엇을 매핑해주는지에 대한 정보가 이름에 드러나면 좋겠네요

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Main.js
> +          </SubList>
이부분도 상수데이터로 표현 가능해보이네요!

2022-04-14 06:50 UTC, younuk23 commented on src/pages/Main/Main.js
> +  ${props => props.theme.wrapper()}
```suggestion
  ${({theme}) => theme.wrapper()}
```
- 구조분해할당을 통해서 좀 더 간결하게 표현할 수 있습니다!

2022-04-14 09:34 UTC, hyodduru commented on public/index.html
> +    ></script>
네 수정하였습니다!

2022-04-14 09:38 UTC, hyodduru commented on src/components/Card/Card.js
> +  .category {
네 수정하였습니다!

2022-04-14 09:40 UTC, hyodduru commented on src/components/Card/Card.js
> +  ];
네 수정하였습니다!

2022-04-14 09:44 UTC, hyodduru commented on src/pages/Main/Components/LectureSlide.js
> +
네 ! 우선 수정하였습니다!

2022-04-14 09:45 UTC, hyodduru commented on src/pages/Main/Components/LectureSlide.js
> +  const getData = async () => {
네 수정하였습니다!

2022-04-14 09:46 UTC, hyodduru commented on src/pages/Main/Components/LectureSlide.js
> +        {cardList && cardList.map(card => <Card key={card.id} card={card} />)}
우와!! 감사합니다!

2022-04-14 09:47 UTC, hyodduru commented on src/pages/Main/Components/Promotion.js
> +const Promotion_Arr = [
네 수정했습니다!

2022-04-14 09:50 UTC, hyodduru commented on src/pages/Main/Main.js
> +  const clickHandler = id => setCurrentId(id);
네 수정하였습니다!

2022-04-14 09:51 UTC, hyodduru commented on src/pages/Main/Main.js
> +};
네 수정하였습니다!

2022-04-14 11:03 UTC, hyodduru commented on src/pages/Main/Main.js
> +          </SubList>
네 수정했습니다!

2022-04-14 11:04 UTC, hyodduru commented on src/pages/Main/Main.js
> +  ${props => props.theme.wrapper()}
네 수정하였습니다!

2022-04-15 06:31 UTC, hyodduru commented on src/components/Card/Card.js
> +  const bgColor = Category_Color.find(list => list.type === categoryTag).color;
네 수정하였습니다!!

2022-04-15 08:28 UTC, younuk23 approved these changes
LGTM 👍
- className 부분 수정안된 부분이 있네요 꼼꼼하게 확인해주세요!
- className 수정은 다음 브랜치에서 작업해주세요~!

2022-04-15 08:28 UTC, merged