[31기 김정수] ADD:로그인 페이지 레이아웃 / 소셜 로그인 구현
wecode-bootcamp-korea/31-2nd-bbooing-frontend pull request #4
Opened 2022-04-14 07:28 UTC by MAGHC

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
소셜로그인 구현(카카오) javascript sdk방식 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.sdk 방식으로 백엔드에 카카오 소셜로그인 access_token 건네주는 작업 

2. 카카오 개발자 페이지에서 필수동의 항목 설정 및 앱 주소 설정 

3.카카오 키값 받아서 index.html 에서 문서에 나온대로 init 실행 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

카카오에서 제공하는 이미지와 문서를 보며 현재 코드에는 존재하지 않지만 엑세스 토큰과 다른 api주소를 활용하여 사용자 정보 받아오기, 로그아웃(연결끊기) 를 해보았습니다. 

restful api 방식과 sdk 방식의 차이점에 대해서 혼자서 찾아본 결과  현재 프로젝트에서 진행시 해야할 일이 변경되는 것은 없으나 

restful api가 좀 더 세세하게 설정하고 활용하기에 좋을 수 있지만 편하기는 sdk가 더 편하다는 결론을 얻었습니다.
그리고 실제로 sdk가 더 구현하기 편해 보여서 sdk 방식으로 구현했습니다.  

<br />

2022-04-14 08:46 UTC, younuk23 requested changes
고생하셨습니다 정수님 문서 잘 찾아보시고 적용하신 노력이 느껴지네요 👍

2022-04-14 08:46 UTC, younuk23 commented on public/index.html
> +      window.Kakao.init('839f9bffa542c41d3348afc1ab875d8a');
- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- 이런 코드상에 유출되면 안되는 정보들은 환경변수를 통해서 관리해주는게 좋습니다
- CRA는 .env 파일을 통해서 편하게 환경변수를 설정할 수 있습니다.
- `.env`파일을 통해서 환경변수 관리해주시고 gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- 참고자료
- [Create React App 공식문서](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env)

2022-04-14 08:46 UTC, younuk23 commented on src/pages/Login/Login.js
> +            fetch('http://10.58.1.126:8000/users/signup', {
api주소는 `config.js` 에서 관리하는 것으로 수정해주세요

API는 `config.js` 파일에서 일괄적으로 관리하면서 import, export 를 통해 사용하는 식으로 관리하는 것이 좋습니다. 그렇지 않을 경우, 백엔드 서버 IP 가 변경되면 fetch 함수를 일일이 찾아서 API 를 직접 수정해 주어야 하기 때문입니다.

아래는 config.js에서 API주소를 관리하는 하나의 예시입니다. 참고하셔서 팀원들과 논의 후 생각하신 방식으로 자유롭게 적용해주세요

```jsx
// src/config.js
const BASE_URL = 'http://10.58.5.151:8000'
const API = {
  product:`${BASE_URL}/products`,
  list:`${BASE_URL}/list`
}

// 사용하는 컴포넌트
import { API } from '../../../config.js';

...

fetch(`${API}/5`).then(...).then(...);
```

위의 경우, 백엔드 IP 가 바뀔 때 `config.js` 에서 IP 만 바꾸어주면 모든 API 가 새로운 IP 에 따라서 변경됩니다. 그렇기 때문에 일일이 fetch 함수를 찾아 API 를 수정해줄 필요가 없습니다.

2022-04-14 08:46 UTC, younuk23 commented on src/pages/Login/Login.js
> +        <MainImg alt="로그인배경이미지" src="images\login background img.jpg" />
```suggestion
        <MainImg alt="로그인배경이미지" src="/images/login background img.jpg" />
```

절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.
- 경로가 계속 "/"가 아니라 "\"로 처리된 것이 많이 보이는데 별다른 이유가 있나요?

2022-04-14 10:24 UTC, MAGHC commented on src/pages/Login/Login.js
> +        <MainImg alt="로그인배경이미지" src="images\login background img.jpg" />
아니요 별다른 이유 없고 그냥 그렇게 습관이 된 것 같습니다 수정하겠습니다!

2022-04-18 02:48 UTC, younuk23 approved these changes
- PR 본문 포맷팅이 깨져있는 부분이 있네요 항상 꼼꼼히 확인해주세요
- .env 파일의 경우 나중에 다른 팀원들의 컴퓨터에서 merge하고 로그인 기능을 확인하고 싶으면 각자의 로컬 컴퓨터에 .env 파일을 만들어 키값을 공유해야되는걸까요? 당장은 그렇게 하더라도 상관 없어 보이지만 혹시 배포를 하게 된다거나 하면 어떻게 키값을 불러와서 처리가능한것인지 궁금합니다
***
- 네 말씀하신 대로입니다. 팀원들이 로컬 개발환경을 설정하기 위해서는 .env 파일이 필요하기에 각자 로컬 컴퓨터에 해당 키값을 공유하는식으로 진행되어야 하고, 배포하게되는경우에는 배포하는 infra에 환경변수를 설정하는 방식을 통해서 진행합니다.
- 환경변수를 사용하는 목적을 크게 두가지로 나눠보면, 1. 핵심적인 보안 키들이 코드상에 드러나지 않도록 숨김, 2.말 그대로 변수들을 환경에 따라 설정할 수 있게 만들어서 각 환경에서 손쉽게 key들을 설정할 수 있도록 해줌(configurable 의 관점) 입니다.
- 실제로 AWS등의 서비스에서는 손쉽게 환경변수를 설정할 수 있는 기능을 제공해줍니다.

2022-04-18 02:48 UTC, merged

2022-04-18 02:49 UTC, younuk23 commented
- 위 환경변수 관련 내용 팀원들과도 공유해주세요~~!!(해당 내용 공부하셔서 정리한 뒤에 발표등을 통해서 동기분들께도 지식공유가 되면 너무 좋겠네요!)