[31기 김효정] 강의 리스트 페이지 레이아웃 완료
wecode-bootcamp-korea/31-2nd-bbooing-frontend pull request #6
Opened 2022-04-14 22:23 UTC by hyodduru

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 공통 컴포넌트로 쓰이는 강의 카드를 강의 리스트 페이지에 렌더링
- filter 부분 레이아웃 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 공통 컴포넌트로 쓰이는 강의 카드를 강의 리스트 페이지에 렌더링
mock data를 활용하여 강의 리스트를 fetch한 뒤 공통 컴포넌트인 강의 카드와 map을 이용하여 화면에 렌더링하였습니다. 

2. filter 부분 레이아웃 
총 4개지 종류의 filter 레이아웃을 함. filter 내에는 카테고리 이름과 해당 리스트들이 담겨 있음. 해당 정보가 담겨있는 상수 데이터와 map을 활용하여 화면에 렌더링하였습니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
map과 상수데이터를 활용하여 화면에 렌더링하는 방식에 더욱 익숙해졌습니다. 반복되는 코드를 줄여주고 코드를 훨씬 가독성이 좋게 만들어주는 것 같아서 앞으로도 계속 활용하려고 합니다. 

filter 부분을 레이아웃할 때 상수데이터 형식을 어떻게 만들어야할지 고민이 많았습니다. 한 filter 내에 category 제목과 그 category에 해당하는 리스트를 함께 보여줘야하는데 어떤 형식으로 데이터를 구성해야할지 조금 헤매다가 filter = [{category : "제목", contents : [리스트들]}] 이런 식으로 한 필터에 담긴 모든 내용을 담아주었습니다. 받아온 데이터를 어떻게 화면에 그려낼지 어떤 데이터 형식으로 저장을 해야할지 좀 더 고민해볼 수 있었습니다. 

<br />

2022-04-15 06:27 UTC, younuk23 requested changes
고생하셨습니다 효정님!
Card 컴포넌트는 이전 PR에서 리뷰받은 내용이 있어서 해당 부분 반영하시고 여기에 rebase 한번 진행해주세요!

2022-04-15 06:27 UTC, younuk23 commented on src/pages/LectureList/LectureList.js
> +    if (className.includes('category') || className.includes('contents'))
- 이런식으로 className을 기반으로 하는 로직을 짜는것은 권장되지는 않습니다.
지금 구현은 되지만 className은 원래 styling을 하기 위해 붙이는 이름이기때문에 추후 스타일링 변경 소요에 따라 이름이 변동될 가능성이 많습니다. 만약 다른 개발자가 아니면 미래의 내가 이 코드를 확인하지 못한 채 className을 변경해버린다면 이 코드는 바로 동작을 제대로 하지 못하게됩니다!

- 의도하는게 특정 요소 바깥부분을 클릭했을 때 어떤 동작을 하는 것이라면 특정 요소의 바깥부분의 클릭을 감지하는 방법이나 DOM method들을 찾아봐서 활용하는게 좀 더 안전한 코드가 될 것 같네요!

2022-04-15 07:00 UTC, hyodduru commented on src/pages/LectureList/LectureList.js
> +    if (className.includes('category') || className.includes('contents'))
우선 해당 classname을 상수데이터로 하여 변수화하였는데 이렇게 하면 안될까요,,?

2022-04-15 08:36 UTC, younuk23 commented on src/pages/LectureList/LectureList.js
> +    if (className.includes('category') || className.includes('contents'))
- 네! className이 변하면 깨지는 건 똑같을 것 같네요
- 그리고 styledComponenets를 사용하고 있는데 해당 로직만을 위해서 className을 추가해야한다는 단점도 있게되네요!
- https://developer.mozilla.org/ko/docs/Web/API/Node/contains 
- 위 페이지 참고하셔서 event가 발생한 target이 Category or Contents DOM인지 파악하는 식으로 진행해보시면 좋겠네요!
- custom hook 세션 학습자료의 useOutsideClick hook 코드보시는것도 참고가 될 것 같네요!

2022-04-15 08:36 UTC, younuk23 commented
컨플릭 해결해주세요!

2022-04-19 06:47 UTC, younuk23 requested changes
이 PR은 아까 구두로 전달드린 부분만 해결해주세요! 그부분 되고 나면 깔끔할 것 같네요!

2022-04-19 23:33 UTC, hyodduru commented on src/pages/LectureList/LectureList.js
> +    if (className.includes('category') || className.includes('contents'))
네 수정하였습니다!

2022-04-20 07:25 UTC, younuk23 commented
컨플릭 해결해주세요~!

2022-04-20 08:09 UTC, younuk23 approved these changes
구두로 리뷰드릴 사항 제외하고는 LGTM 입니다!

2022-04-20 08:09 UTC, younuk23 commented on src/hooks/useWishListCheck.js
> +};
효정님 이부분은 구두로 리뷰드릴게요! 저 한번 찾아와주세요!

2022-04-20 08:09 UTC, merged