ADD: 리뷰페이지 레이아웃 추가
wecode-bootcamp-korea/31-2nd-bbooing-frontend pull request #7
Opened 2022-04-15 13:23 UTC by Jaehyuksssss

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-  디테일 페이지에 있는 리뷰 컴포넌트의  UI 부분을 완성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 통신전 백엔드 DB의 키값에 맞춰서 mock data를 작성하고 데이터가 제대로 들어가는지 확인했습니다.
2. 스타일 컴포넌트를 활용하여 스타일을 주었습니다.
3. 반복되는 UI를 맵 함수를 사용하여 구현했습니다.
4.비구조화 할당을 하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- git 작업을 잘못하다가 작업했던걸 한번 시원하게 날리고 나서 멘탈이 많이 나갔지만 팀원들이 많이 응원해줘서 다시 힘을 냈습니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-16 12:36 UTC, Jaehyuksssss commented
해결하고 리뷰요청 올리겠습니다!

2022-04-18 02:57 UTC, younuk23 commented
git 작업을 잘못하다가 작업했던걸 한번 시원하게 날리고 나서 멘탈이 많이 나갔지만 팀원들이 많이 응원해줘서 다시 힘을 냈습니다.
=> 코드한줄치고 바로바로 커밋남기기..!!
=> 이 계기로 커밋의 소중함을 느끼시면 됬습니다.. 회사가서 날리는것 보다 낫잖아요? :)
***
해결하고 리뷰요청 올리겠습니다!
=> 어떤 것 해결하신다는 말씀이신가요? 컨플릭 말씀하시는거면 해결하고 나서 리뷰요청 라벨붙여주세요~!

2022-04-20 01:36 UTC, younuk23 requested changes
리뷰 확인해주세요!!
기본적인 컨벤션이랑 포맷팅 신경써주세요!
프리티어가 적용이 안되고 있나요??

2022-04-20 01:36 UTC, younuk23 commented on src/components/Review/Comment.js
> +  }
포멧팅, 인덴트가 다 안맞네요 인덴트 맞춰주세요!

2022-04-20 01:36 UTC, younuk23 commented on src/components/Review/Comment.js
> +  img {
div를 스타일드컴포넌트로 만들고, img를 네스팅해서 스타일링 하는것보다 img를 스타일드 컴포넌트로 만드는게 좋지 않을까요?

2022-04-20 01:36 UTC, younuk23 commented on src/components/Review/Review.js
> +  const createComment = () => {
해결된 코멘트들은 resolve 눌러주세요!

2022-04-20 01:36 UTC, younuk23 commented on src/components/Review/Comment.js
> +          <img src={review_image} alt="" />
alt prop 채워주세요

2022-04-20 01:36 UTC, younuk23 commented on src/components/Review/Review.js
> +const Review = () => {
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

2022-04-21 11:05 UTC, merged